test-backend:
  image: python:3.5.3
  services:
    - redis:3.0
    - postgres:9.6.2
  script:
    - cd backend
    - pip install -r requirements.txt
    - cd django
    - py.test

test-frontend:
  image: node:latest
  script:
    - cd frontend
    - yarn
    - yarn run test
