test-backend:
  image: python:3.5.3
  script:
    - cd backend
    - pip install -r requirements.txt
    - cd django
    - py.test

test-frontend:
  image: node:latest
  script:
    - cd frontend
    - yarn
    - yarn run test
