sudo: required

services:
  - docker

before_install:
  - docker -v
  - docker-compose -v

  # Disable services enabled by default
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop

before_script:
  - cd envs/dev
  - docker-compose build
  - docker volume create vol_smart_pgdata && docker volume create vol_smart_data

script:
  - docker-compose up -d
  - docker-compose exec smart_frontend bash -c "./run_tests.sh"
  - docker-compose exec smart_backend bash -c "./run_tests.sh"
  - docker-compose exec smart_backend bash -c "./scripts/isort.sh"
  - docker-compose exec smart_backend bash -c "./scripts/docformatter.sh"
  - docker-compose exec smart_backend bash -c "./scripts/black.sh"
  - docker-compose exec smart_backend bash -c "./scripts/flake8.sh"

after_script:
  - docker-compose down
  - docker volume remove vol_smart_pgdata && docker volume remove vol_smart_data
