postgres:
  image: postgres:9.6.2
  environment:
    - POSTGRES_PASSWORD=my-secret-password
    - POSTGRES_USER=smart
    - POSTGRES_DB=smart
  ports:
    - "5433:5432"
  volumes_from:
    - pgdata

redis:
  image: redis:3.0
  ports:
    - "6379:6379"

pgdata:
  image: tianon/true
  volumes:
    - /var/lib/postgresql/data
