version: '2.1'

services:
  postgres:
    image: postgres:9.6.2
    environment:
      - POSTGRES_PASSWORD=my-secret-password
      - POSTGRES_USER=smart
      - POSTGRES_DB=smart-prod
    volumes:
      - smart_pgdata:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"

  redis:
    image: redis:3.0
    restart: always
    expose:
      - "6379"

  smart_backend:
    build: 
      context: ../../backend/
      dockerfile: Dockerfile.prod
    image: rti/smart-backend-prod:R_0_0_1
    container_name: smart_backend_prod
    volumes:
      - smart_data:/data/
      - smart_static:/code/frontend/
    restart: always
    depends_on:
      - postgres
      - redis
    expose:
      - "8000"
    command: ./runserver_prod.sh

  smart_frontend:
    build: 
      context: ../../frontend/
      dockerfile: Dockerfile.prod
    image: rti/smart-frontend-prod:R_0_0_1
    container_name: smart_frontend_prod
    volumes:
      - smart_static:/var/www/
      - smart_data:/data/
    restart: always
    ports:
      - "${EXTERNAL_FRONTEND_PORT:-80}:80"
    depends_on:
      - smart_backend
    command: nginx -g "daemon off;"

  celery_worker:
    image: rti/smart-backend-prod:R_0_0_1
    volumes:
      - smart_data:/data/
    restart: always
    depends_on:
      - postgres
      - redis
      - smart_backend
    command: ./runcelery.sh

volumes:
  smart_pgdata:
    external:
      name: vol_smart_pgdata_prod
  smart_data:
    external:
      name: vol_smart_data_prod
  smart_static:
    external:
      name: vol_smart_static_prod