version: '2'

services:
  postgres:
    image: postgres:9.6.2
    environment:
      - POSTGRES_PASSWORD=my-secret-password
      - POSTGRES_USER=smart
      - POSTGRES_DB=smart
    ports:
      - "5433:5432"

  redis:
    image: redis:3.0
    ports:
      - "6379:6379"

  pgdata:
    image: tianon/true
    volumes:
      - /var/lib/postgresql/data

  smart_backend:
    container_name: smart_backend
    volumes:
      - ../backend/django:/code
    ports:
      - "8000:8000"
    command: ./runserver.sh

  smart_frontend:
    container_name: smart_frontend
    volumes:
      - ../frontend/:/code
      - /code/node_modules
